### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DefinitelyNotSimon13** [DHBWProjectsIT23/JavaGame#18]
- [ ] Unitmergen
- [ ] Design Hauptmenü/Spiel
- [ ] Leben neben Units anzeigen
- [ ] "Spielgefühl"
  - [ ] Nur auf Felder clicken die Funktionieren
  - [ ] Units auswählen/anclicken und so
- [ ] Units pro Map
- [ ] Code drüber gehen
- [ ] Ende
  - [ ] Textur?
- [ ] Units sterben
- [ ] Infoview?
- [ ] Infofeld richtige Seite
  - [ ] Units richtig anzeigen
- [ ] Testen
- [ ] Logger rausnehmen
- [ ] Testunits etc komplett entfernen
- [ ] README Datei
  - [ ] Anleitung zum Bauen/Ausführen
  - [ ] Spielanleitung
  - [ ] Anleitung zum "Modding"
- [ ] Anleitung/Requirements doppelchecken
- [ ] Logo/Icon
